### ISSUE TITLE
GitHub Action: Upload only diff to FTP

### ISSUE THREAD

**Issue by han16nah** [CollegiumAcademicum/collegiumacademicum.de#71]
Instead of uploading all files in each action (which takes almost 20 mins), can we upload only files that changed?

![grafik](https://github.com/CollegiumAcademicum/collegiumacademicum.de/assets/41050948/c815f0d8-a1ed-452e-9cd2-e274972967da)

**Comment by morris-frank** [comment]
seems there is an option for only new files in lftp, but I tihnk it wouldnt work. Cause the files are all re-build on the action, so technically they are new at that point

**Comment by morris-frank** [comment]
<img width="824" alt="Screenshot 2024-04-22 at 14 01 40" src="https://github.com/CollegiumAcademicum/collegiumacademicum.de/assets/10817735/fbf67fcc-6fca-4bf9-808a-897ca4d09e8f">
actrually seems to work
